[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scan-deals"]
  schedule = "@hourly"

[functions."price-watch"]
  schedule = "@hourly"

[functions."top20-run"]
  schedule = "@hourly"
