import { getStore } from "@netlify/blobs";

export const store = () => getStore({ name: "mtg-deal-hunter", consistency: "strong" });
export const json = (body, status=200) => new Response(JSON.stringify(body), {status, headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
export const keyFor = d => [d.type||"deal",d.store||"",d.name||"",d.url||""].join("|").toLowerCase();
export const clean = v => typeof v === "string" ? v.trim() : v;

let tcgToken=null,tcgTokenExpires=0,mtgjsonTodayPromise=null;
const mtgjsonSetCache=new Map(),cardCache=new Map();
const day=()=>new Date().toISOString().slice(0,10);
const finishOf=f=>String(f||"nonfoil").toLowerCase();

async function getTcgToken(){const publicKey=process.env.TCGPLAYER_PUBLIC_KEY,privateKey=process.env.TCGPLAYER_PRIVATE_KEY;if(!publicKey||!privateKey)return null;if(tcgToken&&Date.now()<tcgTokenExpires-60000)return tcgToken;const body=new URLSearchParams({grant_type:"client_credentials",client_id:publicKey,client_secret:privateKey}),r=await fetch("https://api.tcgplayer.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","accept":"application/json"},body});if(!r.ok)return null;const data=await r.json();if(!data.access_token)return null;tcgToken=data.access_token;tcgTokenExpires=Date.now()+Number(data.expires_in||3600)*1000;return tcgToken}
export async function tcgMarketPrice(card,finish="nonfoil"){const token=await getTcgToken();if(!token)return null;const f=finishOf(finish),productId=f==="etched"?(card.tcgplayer_etched_id||card.tcgplayer_id):card.tcgplayer_id;if(!productId)return null;const r=await fetch(`https://api.tcgplayer.com/pricing/product/${encodeURIComponent(productId)}`,{headers:{authorization:`bearer ${token}`,accept:"application/json"},signal:AbortSignal.timeout(3500)});if(!r.ok)return null;const data=await r.json(),rows=Array.isArray(data.results)?data.results:[];let row=null;if(f==="foil")row=rows.find(x=>/foil/i.test(String(x.subTypeName||""))&&!/reverse/i.test(String(x.subTypeName||"")));else if(f==="nonfoil")row=rows.find(x=>/^normal$/i.test(String(x.subTypeName||"")))||rows.find(x=>!/foil/i.test(String(x.subTypeName||"")));else row=rows.find(x=>Number(x.marketPrice)>0);const p=Number(row?.marketPrice);return p>0?p:null}
function scryfallUsd(card,finish="nonfoil"){const p=card?.prices||{},f=finishOf(finish);if(f==="foil")return p.usd_foil?Number(p.usd_foil):null;if(f==="etched")return p.usd_etched?Number(p.usd_etched):null;return p.usd?Number(p.usd):null}
async function mtgjsonUuid(card){const set=String(card.set||"").toUpperCase();if(!set)return null;let data=mtgjsonSetCache.get(set);if(!data){const r=await fetch(`https://mtgjson.com/api/v5/${encodeURIComponent(set)}.json`,{headers:{accept:"application/json"},signal:AbortSignal.timeout(3500)});if(!r.ok)return null;data=await r.json();mtgjsonSetCache.set(set,data)}const cards=data?.data?.cards||[],found=cards.find(x=>x?.identifiers?.scryfallId===card.id)||cards.find(x=>String(x.number)===String(card.collector_number)&&String(x.name)===String(card.name));return found?.uuid||null}
async function mtgjsonPricesToday(){if(!mtgjsonTodayPromise)mtgjsonTodayPromise=(async()=>{const r=await fetch("https://mtgjson.com/api/v5/AllPricesToday.json",{headers:{accept:"application/json"},signal:AbortSignal.timeout(8000)});if(!r.ok)return null;return r.json()})().catch(()=>null);return mtgjsonTodayPromise}
export async function mtgjsonTcgRetailPrice(card,finish="nonfoil"){try{const uuid=await mtgjsonUuid(card);if(!uuid)return null;const k=`mtgjson-tcg:${uuid}:${finishOf(finish)}`;try{const c=await store().get(k,{type:"json",consistency:"strong"});if(c?.date===day()&&Number(c.price)>0)return Number(c.price)}catch{}const all=await mtgjsonPricesToday(),retail=all?.data?.[uuid]?.paper?.tcgplayer?.retail;if(!retail)return null;const f=finishOf(finish),points=f==="foil"?retail.foil:f==="etched"?retail.etched:retail.normal;if(!points||typeof points!=="object")return null;const dates=Object.keys(points).sort(),p=Number(points[dates.at(-1)]);if(!(p>0))return null;try{await store().setJSON(k,{date:day(),price:p})}catch{}return p}catch{return null}}
async function fetchCard(item){const set=String(item.set||"").toLowerCase(),num=String(item.collector_number||"");const ck=set&&num?`${set}:${num}`:`name:${String(item.card_name||item.name||"").toLowerCase()}`;if(cardCache.has(ck))return cardCache.get(ck);let url;if(set&&num)url=`https://api.scryfall.com/cards/${encodeURIComponent(set)}/${encodeURIComponent(num)}`;else if(item.card_name||item.name)url=`https://api.scryfall.com/cards/named?exact=${encodeURIComponent(item.card_name||item.name)}`;else return null;try{const r=await fetch(url,{headers:{"user-agent":"MTGDealHunter/5.9 reference-resolver",accept:"application/json"},signal:AbortSignal.timeout(3500)});if(!r.ok)return null;const c=await r.json();cardCache.set(ck,c);return c}catch{return null}}
function referenceKey(item){return `refprice:v2:${String(item.set||'').toLowerCase()}:${String(item.collector_number||'').toLowerCase()}:${finishOf(item.finish)}`}
async function readReferenceCache(item){try{const c=await store().get(referenceKey(item),{type:"json",consistency:"strong"});if(c?.date===day()&&Number(c.price)>0)return{price:Number(c.price),source:c.source,cache_hit:true,card_id:c.card_id||null}}catch{}return null}
async function saveReferenceCache(item,ref){if(!(Number(ref?.price)>0))return;try{await store().setJSON(referenceKey(item),{date:day(),price:Number(ref.price),source:ref.source,card_id:ref.card_id||null})}catch{}}
export async function referencePriceForCard(card,finish="nonfoil"){try{const tcg=await tcgMarketPrice(card,finish);if(tcg>0)return{price:tcg,source:"TCGplayer Market",card_id:card.id}}catch{}const sf=scryfallUsd(card,finish);if(sf>0)return{price:sf,source:"Scryfall exact-print USD",card_id:card.id};try{const proxy=await mtgjsonTcgRetailPrice(card,finish);if(proxy>0)return{price:proxy,source:"MTGJSON TCGplayer retail proxy",card_id:card.id}}catch{}return{price:null,source:null,card_id:card.id}}
export async function exactScryfallReference(item){if(Number(item.market_price)>0)return{price:Number(item.market_price),source:item.market_source||"submitted market price",cache_hit:false};if(item.type!=="single")return{price:null,source:null,cache_hit:false};const cached=await readReferenceCache(item);if(cached)return cached;const card=await fetchCard(item);if(!card)return{price:null,source:null,cache_hit:false};const ref=await referencePriceForCard(card,item.finish||"nonfoil");if(Number(ref.price)>0)await saveReferenceCache({...item,set:card.set,collector_number:card.collector_number},ref);return{...ref,cache_hit:false}}
export async function exactScryfallPrice(item){return (await exactScryfallReference(item)).price}
export async function evaluateDeal(raw,threshold=25){const price=Number(raw.price),base={type:clean(raw.type||"single"),name:clean(raw.name||raw.card_name||raw.product_name||"Unnamed deal"),store:clean(raw.store||"Unknown store"),url:clean(raw.url||""),price:Number.isFinite(price)?price:null,detail:clean(raw.detail||[raw.set,raw.collector_number,raw.finish,raw.condition].filter(Boolean).join(" • ")),set:raw.set||null,collector_number:raw.collector_number||null,finish:raw.finish||"nonfoil"};if(!(price>=0))return{...base,qualified:false,rejection_reason:"invalid_listing_price",reference_found:false};let ref;try{ref=await exactScryfallReference(raw)}catch{return{...base,qualified:false,rejection_reason:"reference_lookup_failed",reference_found:false}}const market=Number(ref?.price);if(!(market>0))return{...base,qualified:false,rejection_reason:"reference_price_unavailable",reference_source:ref?.source||null,reference_found:false,reference_cache_hit:Boolean(ref?.cache_hit)};const discount=(1-price/market)*100,out={...base,market_price:market,reference_source:ref.source||null,reference_found:true,reference_cache_hit:Boolean(ref.cache_hit),discount_pct:discount,threshold};if(discount<threshold)return{...out,qualified:false,rejection_reason:"below_discount_threshold",threshold_gap:threshold-discount};return{...out,qualified:true,rejection_reason:null,found_at:new Date().toISOString()}}
export async function normalizeDeal(raw,threshold=25){const x=await evaluateDeal(raw,threshold);if(!x.qualified)return null;const {qualified,rejection_reason,threshold_gap,...deal}=x;return deal}
