import { store, keyFor, evaluateDeal, prefetchScryfallCards } from "./_shared.mjs";
import { marketSources, fetchMarketSource } from './market-sources.mjs';
import { resolveUnresolvedPrintings } from './unresolved-print-resolver.mjs';
const MAX_SOURCES=40,ITEMS_PER_SOURCE=250,MAX_INCOMING=1500,CONCURRENCY=8;
const fetchJSON=async url=>{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(url,{signal:ctl.signal,headers:{"user-agent":"MTGDealHunter/8.2 funnel-telemetry",accept:"application/json"}});if(!r.ok)throw Error(`${r.status} ${url}`);return await r.json()}finally{clearTimeout(t)}};
async function mapLimit(items,limit,fn){const out=[];let next=0;async function worker(){while(next<items.length){const i=next++;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
const addStats=(a,b={})=>{for(const k of ['products_seen','irrelevant_products','noncard_products','variants_seen','unavailable_variants','invalid_price_variants','sealed_variants','nameless_variants','exact_single_variants','unresolved_single_variants'])a[k]=(a[k]||0)+Number(b[k]||0);return a};
export default async(options={})=>{
  const recoveryLimit=Math.max(0,Math.min(32,Number(options.recoveryLimit??32))),prefetchFallbackLimit=Math.max(0,Math.min(8,Number(options.prefetchFallbackLimit??8)));
  const threshold=Number(process.env.DEAL_THRESHOLD||25),incoming=[],unresolved=[],sourceStats=[],candidateOnly=[],parseFunnel={};
  const builtins=marketSources().slice(0,MAX_SOURCES),sourceResults=await mapLimit(builtins,8,fetchMarketSource);
  for(const x of sourceResults.filter(Boolean)){addStats(parseFunnel,x.parse_stats);sourceStats.push({id:x.source?.id,name:x.source?.name,type:x.source?.type,ok:x.ok,raw_items:x.raw_count||0,usable_items:(x.rows||[]).filter(r=>!r.needs_match&&!r.candidate_only).length,unresolved_items:(x.rows||[]).filter(r=>r.needs_match).length,parse_stats:x.parse_stats||{},ms:x.ms||0,error:x.error||null});for(const row of x.rows||[]){if(row.candidate_only)candidateOnly.push(row);else if(row.needs_match)unresolved.push(row);else incoming.push(row)}}
  const recovery=await resolveUnresolvedPrintings(unresolved,{limit:recoveryLimit});incoming.push(...recovery.resolved);
  const remaining=Math.max(0,MAX_SOURCES-builtins.length),urls=[...new Set((process.env.DEAL_FEED_URLS||'').split(',').map(x=>x.trim()).filter(Boolean))].slice(0,remaining),legacy=await mapLimit(urls,8,async(url,idx)=>{const started=Date.now();try{const v=await fetchJSON(url),list=Array.isArray(v)?v:(Array.isArray(v.deals)?v.deals:[]);sourceStats.push({id:`feed-${idx+1}`,name:`Configured feed ${idx+1}`,type:'json',ok:true,raw_items:list.length,usable_items:Math.min(list.length,ITEMS_PER_SOURCE),unresolved_items:0,ms:Date.now()-started});return list.slice(0,ITEMS_PER_SOURCE)}catch(e){sourceStats.push({id:`feed-${idx+1}`,name:`Configured feed ${idx+1}`,type:'json',ok:false,raw_items:0,usable_items:0,unresolved_items:0,error:e.message,ms:Date.now()-started});return[]}});for(const rows of legacy)incoming.push(...(rows||[]));
  const candidates=incoming.slice(0,MAX_INCOMING),prefetch=await prefetchScryfallCards(candidates,{fallbackLimit:prefetchFallbackLimit}),paired=(await mapLimit(candidates,CONCURRENCY,async raw=>{try{return{raw,evaluation:await evaluateDeal(raw,threshold)}}catch{return{raw,evaluation:null}}})).filter(x=>x?.evaluation),evaluations=paired.map(x=>x.evaluation),qualified=evaluations.filter(x=>x.qualified).map(({qualified,rejection_reason,threshold_gap,...x})=>x),rejected=evaluations.filter(x=>!x.qualified),reasonCounts={},referenceFailureCounts={};
  for(const x of rejected){reasonCounts[x.rejection_reason||'unknown']=(reasonCounts[x.rejection_reason||'unknown']||0)+1;if(!x.reference_found&&x.reference_failure_reason){for(const r of String(x.reference_failure_reason).split('+'))referenceFailureCounts[r]=(referenceFailureCounts[r]||0)+1}}
  const failureSamples=paired.filter(x=>!x.evaluation.reference_found&&x.evaluation.reference_failure_reason).slice(0,20).map(({raw,evaluation})=>({reason:evaluation.reference_failure_reason,name:raw.card_name||raw.name||'',raw_title:raw.raw_title||'',variant_title:raw.variant_title||'',sku:raw.sku||'',store:raw.store||'',set:raw.set||'',collector_number:raw.collector_number||'',finish:raw.finish||'',detail:raw.detail||'',url:raw.url||''})),referenceFound=evaluations.filter(x=>x.reference_found).length,referenceCacheHits=evaluations.filter(x=>x.reference_cache_hit).length,resolverRecovered=evaluations.filter(x=>x.resolver_recovered).length,referenceCoverage=evaluations.length?100*referenceFound/evaluations.length:0,nearMisses=rejected.filter(x=>x.rejection_reason==='below_discount_threshold'&&Number.isFinite(x.discount_pct)&&x.discount_pct>0&&x.discount_pct<threshold).sort((a,b)=>b.discount_pct-a.discount_pct).slice(0,10).map(x=>({name:x.name,store:x.store,url:x.url,price:x.price,market_price:x.market_price,discount_pct:x.discount_pct,threshold_gap:threshold-x.discount_pct,reference_source:x.reference_source,detail:x.detail,set:x.set,collector_number:x.collector_number,finish:x.finish}));
  const scannerFunnel={...parseFunnel,products_returned_as_rows:Number(parseFunnel.sealed_variants||0)+Number(parseFunnel.exact_single_variants||0)+Number(parseFunnel.unresolved_single_variants||0),unresolved_pool:unresolved.length,recovery_attempted:recovery.stats.attempted,recovery_resolved:recovery.stats.resolved,exact_candidates_before_recovery:Number(parseFunnel.exact_single_variants||0),exact_candidates_after_recovery:candidates.length,reference_found:referenceFound,reference_missing:evaluations.length-referenceFound,below_threshold:Number(reasonCounts.below_discount_threshold||0),qualified:qualified.length};
  const s=store(),old=(await s.get('feed',{type:'json',consistency:'strong'}))||{deals:[]},map=new Map();for(const d of [...qualified,...(old.deals||[])]){const k=keyFor(d);if(!map.has(k))map.set(k,d)}const cutoff=Date.now()-7*24*60*60*1000,deals=[...map.values()].filter(d=>!d.found_at||new Date(d.found_at).getTime()>=cutoff).sort((a,b)=>(b.discount_pct||0)-(a.discount_pct||0)).slice(0,500);
  await s.setJSON('feed',{updated_at:new Date().toISOString(),scan_mode:options.mode||'scheduled',recovery_limit:recoveryLimit,source_count:builtins.length+urls.length,healthy_sources:sourceStats.filter(x=>x.ok).length,source_stats:sourceStats,scanner_funnel:scannerFunnel,items_seen:sourceStats.reduce((n,x)=>n+Number(x.raw_items||0),0),items_usable:incoming.length,items_evaluated:candidates.length,reference_found:referenceFound,reference_missing:evaluations.length-referenceFound,reference_coverage_pct:referenceCoverage,reference_cache_hits:referenceCacheHits,resolver_recovered:resolverRecovered,name_collector_recovery:recovery.stats,scryfall_prefetch:prefetch,reference_failure_reasons:referenceFailureCounts,reference_failure_samples:failureSamples,unresolved_single_count:unresolved.length,fuzzy_attempted:recovery.stats.attempted,fuzzy_resolved:recovery.stats.resolved,candidate_only_count:candidateOnly.length,qualified_this_run:qualified.length,rejected_this_run:rejected.length,rejection_reasons:reasonCounts,near_misses:nearMisses,threshold,deals,candidates:candidateOnly.slice(0,100)});
};
