import { store, keyFor, normalizeDeal } from "./_shared.mjs";
import { marketSources, fetchMarketSource } from './market-sources.mjs';

const MAX_SOURCES=40,ITEMS_PER_SOURCE=250,MAX_INCOMING=1500,MAX_FUZZY=180,CONCURRENCY=18;
const fetchJSON=async url=>{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),6500);try{const r=await fetch(url,{signal:ctl.signal,headers:{"user-agent":"MTGDealHunter/5.6 broad-sweep","accept":"application/json"}});if(!r.ok)throw Error(`${r.status} ${url}`);return await r.json()}finally{clearTimeout(t)}};
async function mapLimit(items,limit,fn){const out=[];let next=0;async function worker(){while(next<items.length){const i=next++;try{out[i]=await fn(items[i],i)}catch{out[i]=null}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function treatmentMatch(card,t){if(!t)return true;const x=String(t).toLowerCase(),effects=(card.frame_effects||[]).map(String),promos=(card.promo_types||[]).map(String);if(x.includes('borderless'))return card.border_color==='borderless';if(x.includes('extended'))return effects.includes('extendedart');if(x.includes('showcase'))return effects.includes('showcase')||promos.includes('boosterfun');if(x.includes('retro')||x.includes('old-border'))return card.frame==='1997'||effects.includes('retro');if(x.includes('etched'))return (card.finishes||[]).includes('etched');if(x.includes('textured'))return promos.some(v=>v.includes('textured'));if(x.includes('serialized'))return promos.some(v=>v.includes('serialized'));return true}
function finishMatch(card,finish){const f=String(finish||'nonfoil');if(f==='foil')return Boolean(card.foil);if(f==='etched')return (card.finishes||[]).includes('etched');return Boolean(card.nonfoil)}
function scoreCard(raw,c){let score=0;if(norm(c.name)===norm(raw.card_name))score+=60;else return -999;if(raw.set_name_hint){const a=norm(raw.set_name_hint),b=norm(c.set_name);if(a===b)score+=30;else if(a&&b&&(a.includes(b)||b.includes(a)))score+=18;else score-=10}if(finishMatch(c,raw.finish))score+=12;else score-=25;if(raw.treatment){if(treatmentMatch(c,raw.treatment))score+=18;else score-=18}if(c.digital)score-=100;if(c.games&&!c.games.includes('paper'))score-=100;return score}
async function resolveFuzzy(raw){try{const q=`!\"${String(raw.card_name||'').replaceAll('"','')}\" game:paper`,u=`https://api.scryfall.com/cards/search?unique=prints&order=released&dir=desc&q=${encodeURIComponent(q)}`,r=await fetch(u,{headers:{'user-agent':'MTGDealHunter/5.6 exact-matcher','accept':'application/json'},signal:AbortSignal.timeout(4500)});if(!r.ok)return null;const d=await r.json(),ranked=(d.data||[]).map(c=>({c,s:scoreCard(raw,c)})).filter(x=>x.s>=72).sort((a,b)=>b.s-a.s);if(!ranked.length)return null;const best=ranked[0],second=ranked[1];if(second&&best.s-second.s<12)return null;return{...raw,needs_match:false,set:best.c.set,collector_number:best.c.collector_number,name:best.c.name,card_name:best.c.name,finish:raw.finish||'nonfoil',match_score:best.s,match_method:'scryfall-evidence',detail:[raw.detail,`${best.c.set_name} #${best.c.collector_number}`,`match ${best.s}`].filter(Boolean).join(' • ')}}catch{return null}}

export default async () => {
  const threshold=Number(process.env.DEAL_THRESHOLD||25),incoming=[],unresolved=[],sourceStats=[],candidateOnly=[];
  const builtins=marketSources().slice(0,MAX_SOURCES);
  const sourceResults=await mapLimit(builtins,8,fetchMarketSource);
  for(const x of sourceResults.filter(Boolean)){
    sourceStats.push({id:x.source?.id,name:x.source?.name,type:x.source?.type,ok:x.ok,raw_items:x.raw_count||0,usable_items:(x.rows||[]).filter(r=>!r.needs_match&&!r.candidate_only).length,unresolved_items:(x.rows||[]).filter(r=>r.needs_match).length,ms:x.ms||0,error:x.error||null});
    for(const row of x.rows||[]){if(row.candidate_only)candidateOnly.push(row);else if(row.needs_match)unresolved.push(row);else incoming.push(row)}
  }
  const fuzzyBatch=unresolved.slice(0,MAX_FUZZY),resolved=(await mapLimit(fuzzyBatch,8,async(row,i)=>{const v=await resolveFuzzy(row);if(i%25===24)await new Promise(r=>setTimeout(r,120));return v})).filter(Boolean);incoming.push(...resolved);

  const remaining=Math.max(0,MAX_SOURCES-builtins.length),urls=[...new Set((process.env.DEAL_FEED_URLS||"").split(",").map(x=>x.trim()).filter(Boolean))].slice(0,remaining);
  const legacy=await mapLimit(urls,8,async(url,idx)=>{const started=Date.now();try{const v=await fetchJSON(url),list=Array.isArray(v)?v:(Array.isArray(v.deals)?v.deals:[]);sourceStats.push({id:`feed-${idx+1}`,name:`Configured feed ${idx+1}`,type:'json',ok:true,raw_items:list.length,usable_items:Math.min(list.length,ITEMS_PER_SOURCE),unresolved_items:0,ms:Date.now()-started});return list.slice(0,ITEMS_PER_SOURCE)}catch(e){sourceStats.push({id:`feed-${idx+1}`,name:`Configured feed ${idx+1}`,type:'json',ok:false,raw_items:0,usable_items:0,unresolved_items:0,error:e.message,ms:Date.now()-started});return[]}});
  for(const rows of legacy)incoming.push(...(rows||[]));

  const candidates=incoming.slice(0,MAX_INCOMING),normalized=await mapLimit(candidates,CONCURRENCY,async raw=>{try{return await normalizeDeal(raw,threshold)}catch{return null}}),qualified=normalized.filter(Boolean),s=store(),old=(await s.get("feed",{type:"json",consistency:"strong"}))||{deals:[]},map=new Map();
  for(const d of [...qualified,...(old.deals||[])]){const k=keyFor(d);if(!map.has(k))map.set(k,d)}
  const cutoff=Date.now()-7*24*60*60*1000,deals=[...map.values()].filter(d=>!d.found_at||new Date(d.found_at).getTime()>=cutoff).sort((a,b)=>(b.discount_pct||0)-(a.discount_pct||0)).slice(0,500);
  await s.setJSON("feed",{updated_at:new Date().toISOString(),source_count:builtins.length+urls.length,healthy_sources:sourceStats.filter(x=>x.ok).length,source_stats:sourceStats,items_seen:sourceStats.reduce((n,x)=>n+Number(x.raw_items||0),0),items_usable:incoming.length,items_evaluated:candidates.length,unresolved_single_count:unresolved.length,fuzzy_attempted:fuzzyBatch.length,fuzzy_resolved:resolved.length,candidate_only_count:candidateOnly.length,qualified_this_run:qualified.length,threshold,deals,candidates:candidateOnly.slice(0,100)});
};
